/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Decimal = string;
export interface InstantiateMsg {
  curve_coefficient: Decimal;
  protocol_fee_bps: number;
  protocol_fee_destination: string;
  subject_fee_bps: number;
}
export type ExecuteMsg = {
  buy_shares: {
    amount: Uint128;
    subject: string;
  };
} | {
  sell_shares: {
    amount: Uint128;
    subject: string;
  };
};
export type Uint128 = string;
export type QueryMsg = {
  config: {};
} | {
  shares_balance: {
    holder: string;
    subject: string;
  };
} | {
  shares_supply: {
    subject: string;
  };
} | {
  buy_price: {
    amount: Uint128;
    subject: string;
  };
} | {
  sell_price: {
    amount: Uint128;
    subject: string;
  };
} | {
  buy_price_after_fee: {
    amount: Uint128;
    subject: string;
  };
} | {
  sell_price_after_fee: {
    amount: Uint128;
    subject: string;
  };
};
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type Addr = string;
export interface Config {
  curve_coefficient: Decimal;
  protocol_fee_destination: Addr;
  protocol_fee_percent: Decimal;
  subject_fee_percent: Decimal;
}